name: Markdown Tutorial
title: Markdown Tutorial
baseurl: ""
url: "https://www.markdowntutorial.com"
permalink: pretty
exclude: [
    # Folders
    "bin",
    "script",
    "vendor",
    "spec",

    # Files
    "*.sublime*",
    "Gemfile*",
    "CONTRIBUTING.md",
    "README.md",
    "Rakefile",
    "bower.json",
    "config.ru",
  ]

repository: gjtorikian/markdowntutorial.com

assets:
  compress:
    css: true
    js: true
  cdn:
    baseurl: false
    url: null

collections_dir: lessons

collections:
  en:
    output: true
    permalink: lesson/:name/
  es:
    output: true
    permalink: es/lesson/:name/
  fr:
    output: true
    permalink: fr/lesson/:name/
  kr:
    output: true
    permalink: kr/lesson/:name/
  jp:
    output: true
    permalink: jp/lesson/:name/
  nl:
    output: true
    permalink: nl/lesson/:name/
  zh-cn:
    output: true
    permalink: zh-cn/lesson/:name/

defaults:
  - scope:
      path: ""
      type: "en"
    values:
      locale: "en"
  - scope:
      path: ""
      type: "es"
    values:
      locale: "es"
  - scope:
      path: ""
      type: "fr"
    values:
      locale: "fr"
  - scope:
      path: ""
      type: "kr"
    values:
      locale: "kr"
  - scope:
      path: ""
      type: "jp"
    values:
      locale: "jp"
  - scope:
      path: ""
      type: "nl"
    values:
      locale: "nl"
  - scope:
      path: ""
      type: "zh-cn"
    values:
      locale: "zh-cn"
